//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFServiceProxy
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestWFItem", Namespace="http://schemas.datacontract.org/2004/07/GARMCO.AMS.CommonWF.BL.Entities")]
    public partial class RequestWFItem : object
    {
        
        private System.Nullable<int> _actIDField;
        
        private string _actionEmailCcRecipientsField;
        
        private WFServiceProxy.ActivityActionType _activityActionTypeField;
        
        private WFServiceProxy.WorkflowStateType _activityStateTypeField;
        
        private int _activityStatusField;
        
        private WFServiceProxy.GARMCOConstantsActivityType _activityTypeField;
        
        private string _connStringField;
        
        private bool _emailTestModeField;
        
        private string _fromEmailField;
        
        private string _fromNameField;
        
        private string _instanceIDField;
        
        private bool _isThrowEmailExceptionField;
        
        private string _mailServerField;
        
        private int _modifiedByField;
        
        private string _modifiedNameField;
        
        private string _notifyEmailCcRecipientsField;
        
        private bool _requestApprovedField;
        
        private string _requestApprovedRemarksField;
        
        private int _requestCurrentDistMemEmpNoField;
        
        private bool _requestCurrentDistMemOnHoldField;
        
        private string _requestNewCurrentDistMemEmpEmailField;
        
        private string _requestNewCurrentDistMemEmpNameField;
        
        private int _requestNewCurrentDistMemEmpNoField;
        
        private string _requestReassignRemarkField;
        
        private bool _requestRecreateWorkflowField;
        
        private int _requestRountineSeqField;
        
        private string _requestSendBackMessageField;
        
        private string _requestSendBackSubjectField;
        
        private int _requestStatusField;
        
        private WFServiceProxy.GARMCOConstantsRequestTypeStatusCode _requestStatusCodeField;
        
        private WFServiceProxy.GARMCOConstantsRequestType _requestTypeField;
        
        private int _requestTypeIntField;
        
        private int _requestTypeNoField;
        
        private int _retErrorField;
        
        private WFServiceProxy.GARMCOConstantsServiceRole _serviceRoleField;
        
        private string _stateField;
        
        private WFServiceProxy.UserActionType _userActionTypeField;
        
        private string _wfActivityStateField;
        
        private string _workflowBccRecipientsField;
        
        private string _workflowDBConnectionStringField;
        
        private System.Guid _workflowIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> _actID
        {
            get
            {
                return this._actIDField;
            }
            set
            {
                this._actIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _actionEmailCcRecipients
        {
            get
            {
                return this._actionEmailCcRecipientsField;
            }
            set
            {
                this._actionEmailCcRecipientsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WFServiceProxy.ActivityActionType _activityActionType
        {
            get
            {
                return this._activityActionTypeField;
            }
            set
            {
                this._activityActionTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WFServiceProxy.WorkflowStateType _activityStateType
        {
            get
            {
                return this._activityStateTypeField;
            }
            set
            {
                this._activityStateTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _activityStatus
        {
            get
            {
                return this._activityStatusField;
            }
            set
            {
                this._activityStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WFServiceProxy.GARMCOConstantsActivityType _activityType
        {
            get
            {
                return this._activityTypeField;
            }
            set
            {
                this._activityTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _connString
        {
            get
            {
                return this._connStringField;
            }
            set
            {
                this._connStringField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool _emailTestMode
        {
            get
            {
                return this._emailTestModeField;
            }
            set
            {
                this._emailTestModeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _fromEmail
        {
            get
            {
                return this._fromEmailField;
            }
            set
            {
                this._fromEmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _fromName
        {
            get
            {
                return this._fromNameField;
            }
            set
            {
                this._fromNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _instanceID
        {
            get
            {
                return this._instanceIDField;
            }
            set
            {
                this._instanceIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool _isThrowEmailException
        {
            get
            {
                return this._isThrowEmailExceptionField;
            }
            set
            {
                this._isThrowEmailExceptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _mailServer
        {
            get
            {
                return this._mailServerField;
            }
            set
            {
                this._mailServerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _modifiedBy
        {
            get
            {
                return this._modifiedByField;
            }
            set
            {
                this._modifiedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _modifiedName
        {
            get
            {
                return this._modifiedNameField;
            }
            set
            {
                this._modifiedNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _notifyEmailCcRecipients
        {
            get
            {
                return this._notifyEmailCcRecipientsField;
            }
            set
            {
                this._notifyEmailCcRecipientsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool _requestApproved
        {
            get
            {
                return this._requestApprovedField;
            }
            set
            {
                this._requestApprovedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _requestApprovedRemarks
        {
            get
            {
                return this._requestApprovedRemarksField;
            }
            set
            {
                this._requestApprovedRemarksField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _requestCurrentDistMemEmpNo
        {
            get
            {
                return this._requestCurrentDistMemEmpNoField;
            }
            set
            {
                this._requestCurrentDistMemEmpNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool _requestCurrentDistMemOnHold
        {
            get
            {
                return this._requestCurrentDistMemOnHoldField;
            }
            set
            {
                this._requestCurrentDistMemOnHoldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _requestNewCurrentDistMemEmpEmail
        {
            get
            {
                return this._requestNewCurrentDistMemEmpEmailField;
            }
            set
            {
                this._requestNewCurrentDistMemEmpEmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _requestNewCurrentDistMemEmpName
        {
            get
            {
                return this._requestNewCurrentDistMemEmpNameField;
            }
            set
            {
                this._requestNewCurrentDistMemEmpNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _requestNewCurrentDistMemEmpNo
        {
            get
            {
                return this._requestNewCurrentDistMemEmpNoField;
            }
            set
            {
                this._requestNewCurrentDistMemEmpNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _requestReassignRemark
        {
            get
            {
                return this._requestReassignRemarkField;
            }
            set
            {
                this._requestReassignRemarkField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool _requestRecreateWorkflow
        {
            get
            {
                return this._requestRecreateWorkflowField;
            }
            set
            {
                this._requestRecreateWorkflowField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _requestRountineSeq
        {
            get
            {
                return this._requestRountineSeqField;
            }
            set
            {
                this._requestRountineSeqField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _requestSendBackMessage
        {
            get
            {
                return this._requestSendBackMessageField;
            }
            set
            {
                this._requestSendBackMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _requestSendBackSubject
        {
            get
            {
                return this._requestSendBackSubjectField;
            }
            set
            {
                this._requestSendBackSubjectField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _requestStatus
        {
            get
            {
                return this._requestStatusField;
            }
            set
            {
                this._requestStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WFServiceProxy.GARMCOConstantsRequestTypeStatusCode _requestStatusCode
        {
            get
            {
                return this._requestStatusCodeField;
            }
            set
            {
                this._requestStatusCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WFServiceProxy.GARMCOConstantsRequestType _requestType
        {
            get
            {
                return this._requestTypeField;
            }
            set
            {
                this._requestTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _requestTypeInt
        {
            get
            {
                return this._requestTypeIntField;
            }
            set
            {
                this._requestTypeIntField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _requestTypeNo
        {
            get
            {
                return this._requestTypeNoField;
            }
            set
            {
                this._requestTypeNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _retError
        {
            get
            {
                return this._retErrorField;
            }
            set
            {
                this._retErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WFServiceProxy.GARMCOConstantsServiceRole _serviceRole
        {
            get
            {
                return this._serviceRoleField;
            }
            set
            {
                this._serviceRoleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _state
        {
            get
            {
                return this._stateField;
            }
            set
            {
                this._stateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WFServiceProxy.UserActionType _userActionType
        {
            get
            {
                return this._userActionTypeField;
            }
            set
            {
                this._userActionTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _wfActivityState
        {
            get
            {
                return this._wfActivityStateField;
            }
            set
            {
                this._wfActivityStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _workflowBccRecipients
        {
            get
            {
                return this._workflowBccRecipientsField;
            }
            set
            {
                this._workflowBccRecipientsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _workflowDBConnectionString
        {
            get
            {
                return this._workflowDBConnectionStringField;
            }
            set
            {
                this._workflowDBConnectionStringField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid _workflowID
        {
            get
            {
                return this._workflowIDField;
            }
            set
            {
                this._workflowIDField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActivityActionType", Namespace="http://schemas.datacontract.org/2004/07/GARMCO.AMS.CommonWF.BL.Enumeration")]
    public enum ActivityActionType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ActionNotDefined = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ActionApproved = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ActionRejected = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ActionValidated = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ActionAssigned = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ActionReassigned = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ActionSendBackToUser = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ActionClosed = 7,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WorkflowStateType", Namespace="http://schemas.datacontract.org/2004/07/GARMCO.AMS.CommonWF.BL.Enumeration")]
    public enum WorkflowStateType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RequestSubmittedState = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RequestResumedState = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RequestCancelledState = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnknowState = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GARMCOConstants.ActivityType", Namespace="http://schemas.datacontract.org/2004/07/GARMCO.AMS.CommonWF.BL.Helpers")]
    public enum GARMCOConstantsActivityType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoActivity = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Action = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Condition = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Function = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Process = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SendMail = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GARMCOConstants.RequestTypeStatusCode", Namespace="http://schemas.datacontract.org/2004/07/GARMCO.AMS.CommonWF.BL.Helpers")]
    public enum GARMCOConstantsRequestTypeStatusCode : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AssignedToNextServiceProvider = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AssignedToNextApprover = 121,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ReassignedToOtherServiceProvider = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ReassignedToOtherApprover = 122,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ReassignedToOtherValidator = 132,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AssignedtoBuyer = 133,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RequestSent = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Draft = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WaitingForApproval = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AssignedToServiceProvider = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WaitingForUserResponse = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WaitingForVendorResponse = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WorkInProgress = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PRPartiallyClosed = 134,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OQPartiallyClosed = 136,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ApprovedByApprover = 120,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ApprovedByTheCEO = 124,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoActionRequired = 97,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ClosedByServiceProvider = 98,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ClosedByUser = 99,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ClosedByApprover = 123,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ClosedByValidator = 131,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PRClosed = 135,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OQClosed = 137,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PAFPosted = 138,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PRCancelledRejected = 139,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OQCancelledRejected = 140,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CancelledByServiceProvider = 100,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UploadedToJDE = 160,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CancelledByUser = 101,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RejectedByApprover = 110,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RejectedByServiceProvider = 111,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RejectedByValidator = 112,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ForValidation = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ValidatedByValidator = 130,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TicketNotYetProcess = 150,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TicketInProgress = 151,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TicketBooked = 152,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TicketReceivedByUser = 153,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SentBackToUser = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OpenForBidding = 200,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ClosedForBidding = 201,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InitializedBid = 202,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BidSubmitted = 203,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DeclinedToBid = 204,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BidAwarded = 205,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrderCancelled = 206,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SuppliersSelected = 207,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GARMCOConstants.RequestType", Namespace="http://schemas.datacontract.org/2004/07/GARMCO.AMS.CommonWF.BL.Helpers")]
    public enum GARMCOConstantsRequestType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ExpenseRequest = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TravelRequest = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CashAdvanceRequest = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GARMCOConstants.ServiceRole", Namespace="http://schemas.datacontract.org/2004/07/GARMCO.AMS.CommonWF.BL.Helpers")]
    public enum GARMCOConstantsServiceRole : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Approver = 64,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ServiceProvider = 65,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Validator = 151,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserActionType", Namespace="http://schemas.datacontract.org/2004/07/GARMCO.AMS.CommonWF.BL.Enumeration")]
    public enum UserActionType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoAction = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CancelRequest = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ApproveRequest = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RejectRequest = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ValidateRequest = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ReassignRequest = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorDetail", Namespace="http://schemas.datacontract.org/2004/07/GARMCO.AMS.CommonWF.WorkflowService")]
    public partial class ErrorDetail : object
    {
        
        private int ErrorCodeField;
        
        private string ErrorDescriptionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorDescription
        {
            get
            {
                return this.ErrorDescriptionField;
            }
            set
            {
                this.ErrorDescriptionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WorkflowParamEntity", Namespace="http://schemas.datacontract.org/2004/07/GARMCO.AMS.CommonWF.BL.Entities")]
    public partial class WorkflowParamEntity : object
    {
        
        private int ActivityStatusk__BackingFieldField;
        
        private string ConnectionStringk__BackingFieldField;
        
        private bool EmailTestModek__BackingFieldField;
        
        private string FromEmailk__BackingFieldField;
        
        private string FromNamek__BackingFieldField;
        
        private bool IsThrowEmailExceptionk__BackingFieldField;
        
        private string MailServerk__BackingFieldField;
        
        private int ModifiedByk__BackingFieldField;
        
        private string ModifiedNamek__BackingFieldField;
        
        private int RequestTypeIntk__BackingFieldField;
        
        private int RequestTypeNok__BackingFieldField;
        
        private int ReturnErrork__BackingFieldField;
        
        private string WorkflowBccRecipientsk__BackingFieldField;
        
        private string WorkflowDBConnectionStringk__BackingFieldField;
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ActivityStatus>k__BackingField", IsRequired=true)]
        public int ActivityStatusk__BackingField
        {
            get
            {
                return this.ActivityStatusk__BackingFieldField;
            }
            set
            {
                this.ActivityStatusk__BackingFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ConnectionString>k__BackingField", IsRequired=true)]
        public string ConnectionStringk__BackingField
        {
            get
            {
                return this.ConnectionStringk__BackingFieldField;
            }
            set
            {
                this.ConnectionStringk__BackingFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<EmailTestMode>k__BackingField", IsRequired=true)]
        public bool EmailTestModek__BackingField
        {
            get
            {
                return this.EmailTestModek__BackingFieldField;
            }
            set
            {
                this.EmailTestModek__BackingFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<FromEmail>k__BackingField", IsRequired=true)]
        public string FromEmailk__BackingField
        {
            get
            {
                return this.FromEmailk__BackingFieldField;
            }
            set
            {
                this.FromEmailk__BackingFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<FromName>k__BackingField", IsRequired=true)]
        public string FromNamek__BackingField
        {
            get
            {
                return this.FromNamek__BackingFieldField;
            }
            set
            {
                this.FromNamek__BackingFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<IsThrowEmailException>k__BackingField", IsRequired=true)]
        public bool IsThrowEmailExceptionk__BackingField
        {
            get
            {
                return this.IsThrowEmailExceptionk__BackingFieldField;
            }
            set
            {
                this.IsThrowEmailExceptionk__BackingFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<MailServer>k__BackingField", IsRequired=true)]
        public string MailServerk__BackingField
        {
            get
            {
                return this.MailServerk__BackingFieldField;
            }
            set
            {
                this.MailServerk__BackingFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ModifiedBy>k__BackingField", IsRequired=true)]
        public int ModifiedByk__BackingField
        {
            get
            {
                return this.ModifiedByk__BackingFieldField;
            }
            set
            {
                this.ModifiedByk__BackingFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ModifiedName>k__BackingField", IsRequired=true)]
        public string ModifiedNamek__BackingField
        {
            get
            {
                return this.ModifiedNamek__BackingFieldField;
            }
            set
            {
                this.ModifiedNamek__BackingFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<RequestTypeInt>k__BackingField", IsRequired=true)]
        public int RequestTypeIntk__BackingField
        {
            get
            {
                return this.RequestTypeIntk__BackingFieldField;
            }
            set
            {
                this.RequestTypeIntk__BackingFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<RequestTypeNo>k__BackingField", IsRequired=true)]
        public int RequestTypeNok__BackingField
        {
            get
            {
                return this.RequestTypeNok__BackingFieldField;
            }
            set
            {
                this.RequestTypeNok__BackingFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ReturnError>k__BackingField", IsRequired=true)]
        public int ReturnErrork__BackingField
        {
            get
            {
                return this.ReturnErrork__BackingFieldField;
            }
            set
            {
                this.ReturnErrork__BackingFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<WorkflowBccRecipients>k__BackingField", IsRequired=true)]
        public string WorkflowBccRecipientsk__BackingField
        {
            get
            {
                return this.WorkflowBccRecipientsk__BackingFieldField;
            }
            set
            {
                this.WorkflowBccRecipientsk__BackingFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<WorkflowDBConnectionString>k__BackingField", IsRequired=true)]
        public string WorkflowDBConnectionStringk__BackingField
        {
            get
            {
                return this.WorkflowDBConnectionStringk__BackingFieldField;
            }
            set
            {
                this.WorkflowDBConnectionStringk__BackingFieldField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WFServiceProxy.ICommonWFService")]
    public interface ICommonWFService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonWFService/InitiateRequestWorkflow", ReplyAction="http://tempuri.org/ICommonWFService/InitiateRequestWorkflowResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WFServiceProxy.ErrorDetail), Action="http://tempuri.org/ICommonWFService/InitiateRequestWorkflowErrorDetailFault", Name="ErrorDetail", Namespace="http://schemas.datacontract.org/2004/07/GARMCO.AMS.CommonWF.WorkflowService")]
        System.Threading.Tasks.Task<string> InitiateRequestWorkflowAsync(GARMCO.AMS.CommonWF.BL.Entities.RequestWFItem requestItem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonWFService/InitiateRequestWorkflowByInt", ReplyAction="http://tempuri.org/ICommonWFService/InitiateRequestWorkflowByIntResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WFServiceProxy.ErrorDetail), Action="http://tempuri.org/ICommonWFService/InitiateRequestWorkflowByIntErrorDetailFault", Name="ErrorDetail", Namespace="http://schemas.datacontract.org/2004/07/GARMCO.AMS.CommonWF.WorkflowService")]
        System.Threading.Tasks.Task<string> InitiateRequestWorkflowByIntAsync(GARMCO.AMS.CommonWF.BL.Entities.RequestWFItem requestItem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonWFService/UserRequestCancelled", ReplyAction="http://tempuri.org/ICommonWFService/UserRequestCancelledResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WFServiceProxy.ErrorDetail), Action="http://tempuri.org/ICommonWFService/UserRequestCancelledErrorDetailFault", Name="ErrorDetail", Namespace="http://schemas.datacontract.org/2004/07/GARMCO.AMS.CommonWF.WorkflowService")]
        System.Threading.Tasks.Task<int> UserRequestCancelledAsync(GARMCO.AMS.CommonWF.BL.Entities.RequestWFItem requestItem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonWFService/TerminateWorkflowInstance", ReplyAction="http://tempuri.org/ICommonWFService/TerminateWorkflowInstanceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WFServiceProxy.ErrorDetail), Action="http://tempuri.org/ICommonWFService/TerminateWorkflowInstanceErrorDetailFault", Name="ErrorDetail", Namespace="http://schemas.datacontract.org/2004/07/GARMCO.AMS.CommonWF.WorkflowService")]
        System.Threading.Tasks.Task<int> TerminateWorkflowInstanceAsync(GARMCO.AMS.CommonWF.BL.Entities.RequestWFItem requestItem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonWFService/RequestApproved", ReplyAction="http://tempuri.org/ICommonWFService/RequestApprovedResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WFServiceProxy.ErrorDetail), Action="http://tempuri.org/ICommonWFService/RequestApprovedErrorDetailFault", Name="ErrorDetail", Namespace="http://schemas.datacontract.org/2004/07/GARMCO.AMS.CommonWF.WorkflowService")]
        System.Threading.Tasks.Task<int> RequestApprovedAsync(GARMCO.AMS.CommonWF.BL.Entities.RequestWFItem requestItem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonWFService/RequestRejected", ReplyAction="http://tempuri.org/ICommonWFService/RequestRejectedResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WFServiceProxy.ErrorDetail), Action="http://tempuri.org/ICommonWFService/RequestRejectedErrorDetailFault", Name="ErrorDetail", Namespace="http://schemas.datacontract.org/2004/07/GARMCO.AMS.CommonWF.WorkflowService")]
        System.Threading.Tasks.Task<int> RequestRejectedAsync(GARMCO.AMS.CommonWF.BL.Entities.RequestWFItem requestItem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonWFService/RequestValidated", ReplyAction="http://tempuri.org/ICommonWFService/RequestValidatedResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WFServiceProxy.ErrorDetail), Action="http://tempuri.org/ICommonWFService/RequestValidatedErrorDetailFault", Name="ErrorDetail", Namespace="http://schemas.datacontract.org/2004/07/GARMCO.AMS.CommonWF.WorkflowService")]
        System.Threading.Tasks.Task<int> RequestValidatedAsync(GARMCO.AMS.CommonWF.BL.Entities.RequestWFItem requestItem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonWFService/RequestReassigned", ReplyAction="http://tempuri.org/ICommonWFService/RequestReassignedResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WFServiceProxy.ErrorDetail), Action="http://tempuri.org/ICommonWFService/RequestReassignedErrorDetailFault", Name="ErrorDetail", Namespace="http://schemas.datacontract.org/2004/07/GARMCO.AMS.CommonWF.WorkflowService")]
        System.Threading.Tasks.Task<int> RequestReassignedAsync(GARMCO.AMS.CommonWF.BL.Entities.RequestWFItem requestItem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonWFService/InstantiateWorkflow", ReplyAction="http://tempuri.org/ICommonWFService/InstantiateWorkflowResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WFServiceProxy.ErrorDetail), Action="http://tempuri.org/ICommonWFService/InstantiateWorkflowErrorDetailFault", Name="ErrorDetail", Namespace="http://schemas.datacontract.org/2004/07/GARMCO.AMS.CommonWF.WorkflowService")]
        System.Threading.Tasks.Task<string> InstantiateWorkflowAsync(WFServiceProxy.WorkflowParamEntity workflowParam);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface ICommonWFServiceChannel : WFServiceProxy.ICommonWFService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class CommonWFServiceClient : System.ServiceModel.ClientBase<WFServiceProxy.ICommonWFService>, WFServiceProxy.ICommonWFService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CommonWFServiceClient() : 
                base(CommonWFServiceClient.GetDefaultBinding(), CommonWFServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpEndpoint.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CommonWFServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(CommonWFServiceClient.GetBindingForEndpoint(endpointConfiguration), CommonWFServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CommonWFServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CommonWFServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CommonWFServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CommonWFServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CommonWFServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> InitiateRequestWorkflowAsync(GARMCO.AMS.CommonWF.BL.Entities.RequestWFItem requestItem)
        {
            return base.Channel.InitiateRequestWorkflowAsync(requestItem);
        }
        
        public System.Threading.Tasks.Task<string> InitiateRequestWorkflowByIntAsync(GARMCO.AMS.CommonWF.BL.Entities.RequestWFItem requestItem)
        {
            return base.Channel.InitiateRequestWorkflowByIntAsync(requestItem);
        }
        
        public System.Threading.Tasks.Task<int> UserRequestCancelledAsync(GARMCO.AMS.CommonWF.BL.Entities.RequestWFItem requestItem)
        {
            return base.Channel.UserRequestCancelledAsync(requestItem);
        }
        
        public System.Threading.Tasks.Task<int> TerminateWorkflowInstanceAsync(GARMCO.AMS.CommonWF.BL.Entities.RequestWFItem requestItem)
        {
            return base.Channel.TerminateWorkflowInstanceAsync(requestItem);
        }
        
        public System.Threading.Tasks.Task<int> RequestApprovedAsync(GARMCO.AMS.CommonWF.BL.Entities.RequestWFItem requestItem)
        {
            return base.Channel.RequestApprovedAsync(requestItem);
        }
        
        public System.Threading.Tasks.Task<int> RequestRejectedAsync(GARMCO.AMS.CommonWF.BL.Entities.RequestWFItem requestItem)
        {
            return base.Channel.RequestRejectedAsync(requestItem);
        }
        
        public System.Threading.Tasks.Task<int> RequestValidatedAsync(GARMCO.AMS.CommonWF.BL.Entities.RequestWFItem requestItem)
        {
            return base.Channel.RequestValidatedAsync(requestItem);
        }
        
        public System.Threading.Tasks.Task<int> RequestReassignedAsync(GARMCO.AMS.CommonWF.BL.Entities.RequestWFItem requestItem)
        {
            return base.Channel.RequestReassignedAsync(requestItem);
        }
        
        public System.Threading.Tasks.Task<string> InstantiateWorkflowAsync(WFServiceProxy.WorkflowParamEntity workflowParam)
        {
            return base.Channel.InstantiateWorkflowAsync(workflowParam);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpEndpoint))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.TransportCredentialOnly;
                result.Security.Transport.ClientCredentialType = System.ServiceModel.HttpClientCredentialType.Ntlm;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpEndpoint))
            {
                return new System.ServiceModel.EndpointAddress("http://grbhdevt02:8899/CommonWFService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return CommonWFServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpEndpoint);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return CommonWFServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpEndpoint);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpEndpoint,
        }
    }
}
